# Generated by Django 3.2.15 on 2022-09-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_auto_20220922_1934"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
