# Generated by Django 2.2.19 on 2022-11-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_auto_20221102_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="posts/", verbose_name="Картинка"
            ),
        ),
    ]
