# Generated by Django 2.2.19 on 2022-11-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'default_related_name': 'comments',
                'ordering': ('-created',),
                'verbose_name': 'comment',
            },
        ),
    ]
