# Generated by Django 2.2.19 on 2022-11-12 11:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0020_auto_20221111_1304"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("user", "author")},
        ),
    ]
